# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(190, 160, 256, 48))
        self.comboBox.setStyleSheet(
            "QComboBox {\n"
            "    padding: 0 12px;\n"
            "    color: black;\n"
            "    border: 2px solid #8064ea;\n"
            "    border-radius: 8px;\n"
            "    background-color: white\n"
            "}\n"
            "\n"
            "\n"
            "QComboBox:hover, QPushButton:hover {\n"
            "    border-color: #4032ff\n"
            "}\n"
            "\n"
            "QComboBox:editable {\n"
            "    background-color:transparent;\n"
            "    border:none;\n"
            "    color: pink;\n"
            "}\n"
            "\n"
            "QComboBox:!on {\n"
            "\n"
            "}\n"
            "\n"
            "QComboBox:on {\n"
            "\n"
            "}\n"
            "\n"
            "QComboBox QAbstractItemView\n"
            "{\n"
            "    padding: 4px;\n"
            "    border-radius: 8px;\n"
            "    border: 2px solid #8064ea;\n"
            "     /* selection-background-color: red */\n"
            "    background-color: white;\n"
            "}\n"
            "\n"
            "QComboBox::drop-down {\n"
            "    border:none;\n"
            "    background-color:transparent;\n"
            "    min-width: 32px;\n"
            "    color: white\n"
            " }\n"
            "\n"
            " /* Menu */\n"
            "QComboBox:item {\n"
            "    padding: 20px;\n"
            "    border: none;\n"
            "}\n"
            "QComboBox:item:selected {\n"
            "    padding-left: 20px;  /* move text right to make room for tick mark */\n"
            "    border: 2px solid black;\n"
            "}\n"
            "QComboBox:item:checked {\n"
            "    padding-left: 20px;  /* move text right to make room for tick mark */\n"
            "    font-weight: bold;\n"
            "}\n"
            "\n"
            "QComboBox::down-arrow{\n"
            "    right: 4px;\n"
            "    width: 10px;\n"
            "    height: 10px;\n"
            "    image: url(:/newPrefix/assets/images/icons/chevron-down.png);\n"
            "}\n"
            "\n"
            "QComboBox::indicator{\n"
            "    background-color:transparent;\n"
            "    selection-background-color:transparent;\n"
            "    color:transparent;\n"
            "    selection-color:transparent;\n"
            "}"
        )
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Vietnamese"))
        self.comboBox.setItemText(1, _translate("MainWindow", "English"))


import imgs_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
